name: Generate HTML

on:
  push:
    branches: [master]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: Generate HTML
    if: "github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          path: pages
          ref: pages
          ssh-key: ${{ secrets.KEY }}
          repository: isjerryxiao/rushed_dn42_map

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - run: pip install -r req.txt

      - env:
          KEY: ${{ secrets.KEY }}
          GIT_DN42_TOKEN: ${{ secrets.GIT_DN42_TOKEN }}
        shell: bash
        run: |
          set -ex

          pushd pages
          git config user.email "bot@github.com"
          git config user.name "bot"
          git reset --hard f2bb2a8913fc4810ce43446de130572479171d70
          git clean -fxd :/
          popd

          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_ed25519

          trap "shred -v ~/.ssh/id_ed25519" ERR EXIT
          chmod 600 ~/.ssh/id_ed25519
          cat ~/.ssh/config || true
          echo -e "Compression yes\nLogLevel QUIET\nUserKnownHostsFile /dev/null\nStrictHostKeyChecking no" > ~/.ssh/config

          bash gen.sh
          cp index.html isp.json parsed.jsonl.bz2 pages/

          pushd pages
          git add .
          git commit --allow-empty -m "Generated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push --force origin pages
          popd
