name: Generate HTML

on:
  push:
    branches: [master]
  schedule:
    - cron: "5/15 * * * *"

jobs:
  build:
    name: Generate HTML
    if: "github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          path: pages
          ref: pages
          ssh-key: ${{ secrets.KEY }}
          repository: isjerryxiao/rushed_dn42_map

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - run: pip install -r req.txt

      - env:
          GIT_DN42_TOKEN: ${{ secrets.GIT_DN42_TOKEN }}
        shell: bash
        run: |
          set -ex

          pushd pages
          git config user.email "bot@github.com"
          git config user.name "bot"
          git fetch --unshallow
          git reset --hard f2bb2a8913fc4810ce43446de130572479171d70
          git clean -fxd :/
          popd

          bash gen.sh
          cp index.html isp.json parsed.jsonl.bz2 registry.json pages/

          pushd pages
          git add .
          git commit --allow-empty -m "Generated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push --force origin pages
          popd

          # keepalive
          pushd .
          git config user.email "bot@github.com"
          git config user.name "bot"
          git reset --soft HEAD
          git commit --allow-empty -m "[skip ci] keepalive at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          while ! git push origin master; do sleep 10; done
          git show --name-only |grep -Fq '[skip ci] keepalive at'
          git reset --soft HEAD~1
          while ! git push --force origin master; do sleep 10; done
          popd
